### PR TITLE
Kik icon no protocol

### PR DESCRIPTION
**Pull request by austinhallock**
depends on https://github.com/claydotio/clay-mobile/pull/197

### CODE REVIEW

**Comment by Zolmeister** [comment]
done

**Comment by austinhallock** [comment]
updated, rebased

**Comment by Zolmeister** [comment]
looks good, waiting on #197

**Comment by austinhallock** [comment]
rebased (removed dependency on 197)

**Comment by Zolmeister** [comment]
conflicts

**Comment by austinhallock** [comment]
master merged

**Pull request merged**
